interface=wlan0
bind-interfaces
dhcp-range=172.14.1.10,172.14.1.99,255.255.255.0,24h
dhcp-option=3,172.14.1.1
dhcp-option=6,172.14.1.1
domain-needed
bogus-priv
no-resolv
log-dhcp

# BEGIN ARLO MANAGER CAMERAS
# Garage
dhcp-host=fc:9c:98:3a:33:e7,172.14.1.15
# Backyard
dhcp-host=fc:9c:98:39:ea:e9,172.14.1.21
# END ARLO MANAGER CAMERAS
